apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnc-research-example
  namespace: research-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vnc-research-example
  template:
    metadata:
      labels:
        app: vnc-research-example
    spec:
      containers:
        - name: vnc-research-example
          image: ghcr.io/mikethebuddy/example-research-image:1.0.0
          ports:
            - containerPort: 6080
            - containerPort: 5901
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault